import {
  BedSingle,
  Building2,
  BusFront,
  Coffee,
  Croissant,
  Dumbbell,
  Flower2,
  Gem,
  Hotel,
  MapPin,
  Martini,
  Mountain,
  Palmtree,
  PartyPopper,
  Plane,
  Repeat2,
  ShieldCheck,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  SquareParking,
  Sun,
  TentTree,
  ThermometerSun,
  Timer,
  UmbrellaOff,
  Undo2,
  Waves,
  type LucideIcon,
} from "lucide-react";

const FILTER_ICONS: Record<string, LucideIcon> = {
  party: PartyPopper,
  sun: Sun,
  warm: ThermometerSun,
  norain: UmbrellaOff,
  snow: Snowflake,
  mountains: Mountain,
  active: Dumbbell,
  allinclusive: Martini,
  hotel: Hotel,
  apartment: Building2,
  resort: Palmtree,
  hostel: BedSingle,
  glamping: TentTree,
  bnb: Coffee,
  boutique: Gem,
  spa: Flower2,
  pool: Waves,
  citycenter: MapPin,
  breakfast: Croissant,
  seaview: Waves,
  freecancel: Undo2,
  aircon: Snowflake,
  parking: SquareParking,
  gym: Dumbbell,
  airporttransfer: BusFront,
  bigcity: Building2,
  seaside: Waves,
  safe: ShieldCheck,
  direct: Plane,
  onestop: Repeat2,
  shortflight: Timer,
};

export function FilterIcon({ id, className = "h-4 w-4" }: { id: string; className?: string }) {
  const Icon = id.startsWith("ai-") ? Sparkles : (FILTER_ICONS[id] ?? SlidersHorizontal);
  return <Icon className={className} aria-hidden="true" />;
}
